/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./*.html"],
  theme: {
      extend: {
          "colors": {
              "surface-container": "#efedec",
              "secondary-fixed": "#ffdbcc",
              "primary-fixed": "#ffd8e8",
              "deep-plum": "#5E3E4D",
              "tertiary-fixed": "#f1dfd6",
              "primary-fixed-dim": "#e6bbcd",
              "error": "#ba1a1a",
              "on-secondary-container": "#7a5c4f",
              "paper-white": "#FDFDFD",
              "tertiary": "#392f29",
              "surface-container-high": "#eae8e6",
              "on-secondary-fixed-variant": "#5b4135",
              "on-primary": "#ffffff",
              "background": "#fbf9f7",
              "on-secondary-fixed": "#2b160d",
              "surface-dim": "#dbdad8",
              "inverse-primary": "#e6bbcd",
              "surface-tint": "#775464",
              "soft-blush": "#C5A192",
              "primary": "#452836",
              "on-surface": "#1b1c1b",
              "surface-container-highest": "#e4e2e0",
              "surface-container-lowest": "#ffffff",
              "tertiary-fixed-dim": "#d4c3ba",
              "secondary-fixed-dim": "#e5beaf",
              "inverse-surface": "#30302f",
              "on-tertiary-fixed": "#231a14",
              "surface-bright": "#fbf9f7",
              "on-tertiary-container": "#c3b3aa",
              "primary-container": "#5e3e4d",
              "error-container": "#ffdad6",
              "on-background": "#1b1c1b",
              "secondary": "#75584b",
              "on-secondary": "#ffffff",
              "on-primary-fixed": "#2d1320",
              "surface-variant": "#e4e2e0",
              "surface": "#fbf9f7",
              "on-tertiary-fixed-variant": "#50443e",
              "tertiary-container": "#51453e",
              "on-error-container": "#93000a",
              "on-error": "#ffffff",
              "outline": "#807478",
              "muted-taupe": "#8B7D75",
              "outline-variant": "#d2c3c7",
              "secondary-container": "#ffd7c7",
              "on-surface-variant": "#4e4448",
              "inverse-on-surface": "#f2f0ee",
              "primary-fixed-variant": "#5b3c4a",
              "on-primary-container": "#ffd8e8",
              "scrim": "#000000",
              "shadow": "#000000"
          },
          "fontFamily": {
              "label-md": "Manrope",
              "display-md": "Libre Caslon Text",
              "headline-md": "Libre Caslon Text",
              "display-sm": "Libre Caslon Text",
              "label-lg": "Manrope",
              "label-sm": "Manrope",
              "title-lg": "Manrope",
              "title-md": "Manrope",
              "body-lg": "Manrope",
              "body-sm": "Manrope",
              "body-md": "Manrope",
              "title-sm": "Manrope",
              "headline-sm": "Libre Caslon Text",
              "headline-lg": "Libre Caslon Text",
              "display-lg": "Libre Caslon Text"
          },
          "fontSize": {
              "label-md": "0.75rem",
              "display-md": "2.8125rem",
              "headline-md": "1.75rem",
              "display-sm": "2.25rem",
              "label-lg": "0.875rem",
              "label-sm": "0.6875rem",
              "title-lg": "1.375rem",
              "title-md": "1rem",
              "body-lg": "1rem",
              "body-sm": "0.75rem",
              "body-md": "0.875rem",
              "title-sm": "0.875rem",
              "headline-sm": "1.5rem",
              "headline-lg": "2rem",
              "display-lg": "3.571rem",
              
              "display-lg-mobile": "2.5rem",
              "display-md-mobile": "2.25rem",
              "display-sm-mobile": "2rem",
              "headline-lg-mobile": "1.75rem",
              "headline-md-mobile": "1.5rem",
              "headline-sm-mobile": "1.25rem"
          },
          "fontWeight": {
              "label-md": "500",
              "display-md": "400",
              "headline-md": "400",
              "display-sm": "400",
              "label-lg": "500",
              "label-sm": "500",
              "title-lg": "400",
              "title-md": "500",
              "body-lg": "400",
              "body-sm": "400",
              "body-md": "400",
              "title-sm": "500",
              "headline-sm": "400",
              "headline-lg": "400",
              "display-lg": "400"
          },
          "lineHeight": {
              "label-md": "1.3",
              "display-md": "1.2",
              "headline-md": "1.2",
              "display-sm": "1.2",
              "label-lg": "1.4",
              "label-sm": "1.4",
              "title-lg": "1.3",
              "title-md": "1.5",
              "body-lg": "1.5",
              "body-sm": "1.3",
              "body-md": "1.4",
              "title-sm": "1.4",
              "headline-sm": "1.3",
              "headline-lg": "1.2",
              "display-lg": "1.1"
          },
          "letterSpacing": {
              "label-md": "0.03em",
              "display-md": "0em",
              "headline-md": "0em",
              "display-sm": "0em",
              "label-lg": "0.01em",
              "label-sm": "0.03em",
              "title-lg": "0em",
              "title-md": "0.01em",
              "body-lg": "0.03em",
              "body-sm": "0.03em",
              "body-md": "0.01em",
              "title-sm": "0.01em",
              "headline-sm": "0em",
              "headline-lg": "0em",
              "display-lg": "0em"
          },
          "spacing": {
              "margin-mobile": "1.25rem",
              "margin-desktop": "3rem",
              "stack-sm": "1rem",
              "stack-md": "2.5rem",
              "stack-lg": "5rem",
              "section-gap": "7.5rem"
          },
          "maxWidth": {
              "container-max": "1200px",
              "content-narrow": "800px"
          },
          "borderRadius": {
              "ui-sm": "0.25rem",
              "ui-md": "0.5rem",
              "ui-lg": "1rem",
              "image-corner": "1.5rem"
          },
          "keyframes": {
              "fade-in-up": {
                  "0%": { opacity: 0, transform: "translateY(20px)" },
                  "100%": { opacity: 1, transform: "translateY(0)" }
              }
          },
          "animation": {
              "fade-in-up": "fade-in-up 0.8s ease-out forwards"
          }
      }
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
}
