/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: "class",
    content: ["./*.html"],
    theme: {
        extend: {
            "colors": {
                "surface-container": "#efedec",
                "secondary-fixed": "#ffdbcc",
                "primary-fixed": "#ffd8e8",
                "deep-plum": "#5E3E4D",
                "tertiary-fixed": "#f1dfd6",
                "primary-fixed-dim": "#e6bbcd",
                "error": "#ba1a1a",
                "on-secondary-container": "#7a5c4f",
                "paper-white": "#FDFDFD",
                "tertiary": "#392f29",
                "surface-container-high": "#eae8e6",
                "on-secondary-fixed-variant": "#5b4135",
                "on-primary": "#ffffff",
                "background": "#fbf9f7",
                "on-secondary-fixed": "#2b160d",
                "surface-dim": "#dbdad8",
                "inverse-primary": "#e6bbcd",
                "surface-tint": "#775464",
                "soft-blush": "#C5A192",
                "primary": "#452836",
                "on-surface": "#1b1c1b",
                "surface-container-highest": "#e4e2e0",
                "surface-container-lowest": "#ffffff",
                "tertiary-fixed-dim": "#d4c3ba",
                "secondary-fixed-dim": "#e5beaf",
                "inverse-surface": "#30302f",
                "on-tertiary-fixed": "#231a14",
                "surface-bright": "#fbf9f7",
                "on-tertiary-container": "#c3b3aa",
                "primary-container": "#5e3e4d",
                "error-container": "#ffdad6",
                "on-background": "#1b1c1b",
                "secondary": "#75584b",
                "on-secondary": "#ffffff",
                "on-primary-fixed": "#2d1320",
                "surface-variant": "#e4e2e0",
                "surface": "#fbf9f7",
                "on-tertiary-fixed-variant": "#50443e",
                "tertiary-container": "#51453e",
                "on-error-container": "#93000a",
                "on-error": "#ffffff",
                "outline": "#807478",
                "muted-taupe": "#8B7D75",
                "outline-variant": "#d2c3c7",
                "secondary-container": "#ffd7c7",
                "on-surface-variant": "#4e4448",
                "on-primary-fixed-variant": "#5d3d4c",
                "on-primary-container": "#d5abbc",
                "medical-gray": "#EDEDED",
                "on-tertiary": "#ffffff",
                "surface-container-low": "#f5f3f1",
                "inverse-on-surface": "#f2f0ee"
            },
            "borderRadius": {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            "spacing": {
                "stack-md": "32px",
                "base": "8px",
                "stack-sm": "16px",
                "section-mobile": "64px",
                "gutter": "24px",
                "margin-edge": "40px",
                "section-desktop": "120px"
            },
            "fontFamily": {
                "display-lg": ["Libre Caslon Text"],
                "headline-xl": ["Libre Caslon Text"],
                "headline-lg": ["Libre Caslon Text"],
                "headline-md": ["Libre Caslon Text"],
                "body-lg": ["Manrope"],
                "body-md": ["Manrope"],
                "label-md": ["Manrope"],
                "label-sm": ["Manrope"]
            },
            "fontSize": {
                "display-lg-mobile": ["40px", {"lineHeight": "48px", "fontWeight": "400"}],
                "display-lg": ["64px", {"lineHeight": "72px", "letterSpacing": "-0.02em", "fontWeight": "400"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "400"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "400"}],
                "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}],
                "label-sm": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "headline-xl": ["48px", {"lineHeight": "56px", "fontWeight": "400"}],
                "headline-xl-mobile": ["32px", {"lineHeight": "40px", "fontWeight": "400"}]
            }
        }
    },
    plugins: [
        require('@tailwindcss/forms'),
        require('@tailwindcss/container-queries')
    ],
}
